name: rush_sdk
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: any
  camera: ^0.11.0+1
  url_launcher: ^6.1.6
  equatable: ^2.0.5
  photo_view: ^0.14.0
  loading_overlay: ^0.3.0

  freezed_annotation: ^2.4.1
  permission_handler: ^11.3.0
  lottie: ^2.0.0
  flutter_svg: ^2.0.5
  flutter_sticky_header: ^0.6.5
  webview_flutter: ^4.4.2
  shimmer: ^3.0.0
  dotted_border: ^2.1.0
  auto_size_text: ^3.0.0
  scroll_to_index: ^3.0.1

  appsflyer_sdk: ^6.14.3
  facebook_app_events: ^0.19.0
  notifly_flutter: ^1.5.0
  sentry_flutter: ^7.17.0
  sentry_link: ^0.3.0
  sentry_logging: ^7.14.0
  sentry_dio: ^7.14.0
  fluttertoast: ^8.2.8
  
  # Network
  cloudflare: ^3.2.1+1
  cached_network_image: ^3.2.3
  flutter_cache_manager: ^3.3.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  native_dio_adapter: ^1.3.0

  # graphql
  graphql: ^5.1.3
  hasura_connect: ^5.0.0+3

  # local storages
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1 
  path_provider: ^2.0.15

  # UTIL
  image_picker: ^1.0.7
  app_links: ^3.4.3
  flutter_dotenv: ^5.1.0
  share_plus: ^7.1.0
  device_info_plus: ^9.1.2
  package_info_plus: ^4.0.2

  # Firebase
  firebase_core: ^2.27.0
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.10
  firebase_crashlytics: ^3.4.18
  firebase_dynamic_links: ^5.4.17
  cloud_functions: ^4.6.8
  infinite_scroll_pagination: ^3.2.0
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

flutter_intl:
  enabled: true