// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsProd {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1bokiFosg8xtGQbf8aUM5PyZH6WZ2IA',
    appId: '1:827407145753:android:8cb19fa5f0bdfe73a48388',
    messagingSenderId: '827407145753',
    projectId: 'epicone-88e1f',
    storageBucket: 'epicone-88e1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZrn6m64p2fyw6TYqLaiPJfEoq2w7ksTc',
    appId: '1:827407145753:ios:3e2a477c1001e0dfa48388',
    messagingSenderId: '827407145753',
    projectId: 'epicone-88e1f',
    storageBucket: 'epicone-88e1f.appspot.com',
    androidClientId:
        '827407145753-brlma7n0i3hh65e0t0h0e48pg400vagr.apps.googleusercontent.com',
    iosClientId:
        '827407145753-1ive1ou0vj55iamgmlrle4eg7e8sfa9b.apps.googleusercontent.com',
    iosBundleId: 'io.epiccorp.one',
  );
}
